package com.gms.model.admin;

public class GridCase {
	
	int GRVDETID;
	int CASEID;
	String HIERCODE;
	int HIERORDER;
	String TAT_START_DATE;
	String TAT_ACTUAL_END_DATE;
	String CURRENT_ROW_COMPLETED;
	String CURRENT_ROW_ACTIVE;
	String IS_ACTIVE;
	int INVESTIGATOR_EMPLOYEE_ID;
	String NAME;
	String RE_ASSIGN;
	String REOPEN_DATE;
	int REOPEN_HIERORDER;
	String REOPEN_REASON;
	int BUFFERDAYS;
	
    String CASENUMBER; 
    String MAIN_CATEGORY_CODE;
    String SUB_CATEGORY_CODE; 
    String TAT_EXTENDED; 
    int TAT_EXTENDED_EMPLOYEE_ID; 
    String TAT_END_DATE ;
    String INVESTIGATOR_NEEDED;
    String INVESTIGATOR_ASSIGNED;
    String DECISION_ARRIVED; 
    String REASON_NO_DECISION; 
    String DECISION_REPORT; 
    String DECISION_SIGNATURE; 
    String EMP_ACCEPT_DECISION; 
    String EMP_NOT_ACCEPT_REASON; 
    String DECISION_REPORT_DATE; 
    String DECISION_REPORT_CONTENT; 
    String flagButton;
    String TATEXT_REASON;
    int isTatExtn;
	
	public GridCase(int cASEID, String hIERCODE, int hIERORDER, String tAT_START_DATE, String tAT_ACTUAL_END_DATE,
			String cURRENT_ROW_COMPLETED, String cURRENT_ROW_ACTIVE, String iS_ACTIVE, int iNVESTIGATOR_EMPLOYEE_ID,
			String nAME, String rE_ASSIGN, String fLAGBUTTON, String tATEXT_REASON) {
		super();
		CASEID = cASEID;
		HIERCODE = hIERCODE;
		HIERORDER = hIERORDER;
		TAT_START_DATE = tAT_START_DATE;
		TAT_ACTUAL_END_DATE = tAT_ACTUAL_END_DATE;
		CURRENT_ROW_COMPLETED = cURRENT_ROW_COMPLETED;
		CURRENT_ROW_ACTIVE = cURRENT_ROW_ACTIVE;
		IS_ACTIVE = iS_ACTIVE;
		INVESTIGATOR_EMPLOYEE_ID = iNVESTIGATOR_EMPLOYEE_ID;
		NAME = nAME;
		RE_ASSIGN = rE_ASSIGN;
		flagButton = fLAGBUTTON;
		TATEXT_REASON = tATEXT_REASON;
	}

	public GridCase(int cASEID, String hIERCODE, int hIERORDER, String tAT_START_DATE, String tAT_ACTUAL_END_DATE,
			String cURRENT_ROW_COMPLETED, String cURRENT_ROW_ACTIVE, String iS_ACTIVE, int iNVESTIGATOR_EMPLOYEE_ID,
			String nAME) {
		super();
		CASEID = cASEID;
		HIERCODE = hIERCODE;
		HIERORDER = hIERORDER;
		TAT_START_DATE = tAT_START_DATE;
		TAT_ACTUAL_END_DATE = tAT_ACTUAL_END_DATE;
		CURRENT_ROW_COMPLETED = cURRENT_ROW_COMPLETED;
		CURRENT_ROW_ACTIVE = cURRENT_ROW_ACTIVE;
		IS_ACTIVE = iS_ACTIVE;
		INVESTIGATOR_EMPLOYEE_ID = iNVESTIGATOR_EMPLOYEE_ID;
		NAME = nAME;
	}
	
	public GridCase(int cASEID, String hIERCODE, int hIERORDER, String tAT_START_DATE, String tAT_ACTUAL_END_DATE,
			String cURRENT_ROW_COMPLETED, String cURRENT_ROW_ACTIVE, String iS_ACTIVE, int iNVESTIGATOR_EMPLOYEE_ID,
			String nAME,String fLAGBUTTON, String tATEXT_REASON) {
		super();
		CASEID = cASEID;
		HIERCODE = hIERCODE;
		HIERORDER = hIERORDER;
		TAT_START_DATE = tAT_START_DATE;
		TAT_ACTUAL_END_DATE = tAT_ACTUAL_END_DATE;
		CURRENT_ROW_COMPLETED = cURRENT_ROW_COMPLETED;
		CURRENT_ROW_ACTIVE = cURRENT_ROW_ACTIVE;
		IS_ACTIVE = iS_ACTIVE;
		INVESTIGATOR_EMPLOYEE_ID = iNVESTIGATOR_EMPLOYEE_ID;
		NAME = nAME;
		flagButton = fLAGBUTTON;
		TATEXT_REASON = tATEXT_REASON;
	}
	
	public GridCase(int cASEID, String hIERCODE, int hIERORDER, String tAT_START_DATE, String tAT_ACTUAL_END_DATE,
			String cURRENT_ROW_COMPLETED, String cURRENT_ROW_ACTIVE, String iS_ACTIVE, int iNVESTIGATOR_EMPLOYEE_ID,
			String nAME,int bUFFERDAYS, String TATEXT_REASON) {
		super();
		CASEID = cASEID;
		HIERCODE = hIERCODE;
		HIERORDER = hIERORDER;
		TAT_START_DATE = tAT_START_DATE;
		TAT_ACTUAL_END_DATE = tAT_ACTUAL_END_DATE;
		CURRENT_ROW_COMPLETED = cURRENT_ROW_COMPLETED;
		CURRENT_ROW_ACTIVE = cURRENT_ROW_ACTIVE;
		IS_ACTIVE = iS_ACTIVE;
		INVESTIGATOR_EMPLOYEE_ID = iNVESTIGATOR_EMPLOYEE_ID;
		NAME = nAME;
		BUFFERDAYS=bUFFERDAYS;
		this.TATEXT_REASON = TATEXT_REASON;
	}
	
	
	public int getBUFFERDAYS() {
		return BUFFERDAYS;
	}
	public void setBUFFERDAYS(int bUFFERDAYS) {
		BUFFERDAYS = bUFFERDAYS;
	}
	public int getGRVDETID() {
		return GRVDETID;
	}
	public void setGRVDETID(int gRVDETID) {
		GRVDETID = gRVDETID;
	}
	public String getREOPEN_DATE() {
		return REOPEN_DATE;
	}

	public void setREOPEN_DATE(String rEOPEN_DATE) {
		REOPEN_DATE = rEOPEN_DATE;
	}

	public int getREOPEN_HIERORDER() {
		return REOPEN_HIERORDER;
	}

	public void setREOPEN_HIERORDER(int rEOPEN_HIERORDER) {
		REOPEN_HIERORDER = rEOPEN_HIERORDER;
	}

	public String getREOPEN_REASON() {
		return REOPEN_REASON;
	}

	public void setREOPEN_REASON(String rEOPEN_REASON) {
		REOPEN_REASON = rEOPEN_REASON;
	}

	public String getRE_ASSIGN() {
		return RE_ASSIGN;
	}

	public void setRE_ASSIGN(String rE_ASSIGN) {
		RE_ASSIGN = rE_ASSIGN;
	}

	public int getCASEID() {
		return CASEID;
	}
	public void setCASEID(int cASEID) {
		CASEID = cASEID;
	}
	public String getHIERCODE() {
		return HIERCODE;
	}
	public void setHIERCODE(String hIERCODE) {
		HIERCODE = hIERCODE;
	}
	public int getHIERORDER() {
		return HIERORDER;
	}
	public void setHIERORDER(int hIERORDER) {
		HIERORDER = hIERORDER;
	}
	public String getTAT_START_DATE() {
		return TAT_START_DATE;
	}
	public void setTAT_START_DATE(String tAT_START_DATE) {
		TAT_START_DATE = tAT_START_DATE;
	}
	public String getTAT_ACTUAL_END_DATE() {
		return TAT_ACTUAL_END_DATE;
	}
	public void setTAT_ACTUAL_END_DATE(String tAT_ACTUAL_END_DATE) {
		TAT_ACTUAL_END_DATE = tAT_ACTUAL_END_DATE;
	}
	public String getCURRENT_ROW_COMPLETED() {
		return CURRENT_ROW_COMPLETED;
	}
	public void setCURRENT_ROW_COMPLETED(String cURRENT_ROW_COMPLETED) {
		CURRENT_ROW_COMPLETED = cURRENT_ROW_COMPLETED;
	}
	public String getCURRENT_ROW_ACTIVE() {
		return CURRENT_ROW_ACTIVE;
	}
	public void setCURRENT_ROW_ACTIVE(String cURRENT_ROW_ACTIVE) {
		CURRENT_ROW_ACTIVE = cURRENT_ROW_ACTIVE;
	}
	public String getIS_ACTIVE() {
		return IS_ACTIVE;
	}
	public void setIS_ACTIVE(String iS_ACTIVE) {
		IS_ACTIVE = iS_ACTIVE;
	}
	public int getINVESTIGATOR_EMPLOYEE_ID() {
		return INVESTIGATOR_EMPLOYEE_ID;
	}
	public void setINVESTIGATOR_EMPLOYEE_ID(int iNVESTIGATOR_EMPLOYEE_ID) {
		INVESTIGATOR_EMPLOYEE_ID = iNVESTIGATOR_EMPLOYEE_ID;
	}
	public String getNAME() {
		return NAME;
	}
	public void setNAME(String nAME) {
		NAME = nAME;
	}
	
	public String getCASENUMBER() {
		return CASENUMBER;
	}
	public void setCASENUMBER(String cASENUMBER) {
		CASENUMBER = cASENUMBER;
	}
	public String getMAIN_CATEGORY_CODE() {
		return MAIN_CATEGORY_CODE;
	}
	public void setMAIN_CATEGORY_CODE(String mAIN_CATEGORY_CODE) {
		MAIN_CATEGORY_CODE = mAIN_CATEGORY_CODE;
	}
	public String getSUB_CATEGORY_CODE() {
		return SUB_CATEGORY_CODE;
	}
	public void setSUB_CATEGORY_CODE(String sUB_CATEGORY_CODE) {
		SUB_CATEGORY_CODE = sUB_CATEGORY_CODE;
	}
	public String getTAT_EXTENDED() {
		return TAT_EXTENDED;
	}
	public void setTAT_EXTENDED(String tAT_EXTENDED) {
		TAT_EXTENDED = tAT_EXTENDED;
	}
	public int getTAT_EXTENDED_EMPLOYEE_ID() {
		return TAT_EXTENDED_EMPLOYEE_ID;
	}
	public void setTAT_EXTENDED_EMPLOYEE_ID(int tAT_EXTENDED_EMPLOYEE_ID) {
		TAT_EXTENDED_EMPLOYEE_ID = tAT_EXTENDED_EMPLOYEE_ID;
	}
	public String getTAT_END_DATE() {
		return TAT_END_DATE;
	}
	public void setTAT_END_DATE(String tAT_END_DATE) {
		TAT_END_DATE = tAT_END_DATE;
	}
	public String getINVESTIGATOR_NEEDED() {
		return INVESTIGATOR_NEEDED;
	}
	public void setINVESTIGATOR_NEEDED(String iNVESTIGATOR_NEEDED) {
		INVESTIGATOR_NEEDED = iNVESTIGATOR_NEEDED;
	}
	public String getINVESTIGATOR_ASSIGNED() {
		return INVESTIGATOR_ASSIGNED;
	}
	public void setINVESTIGATOR_ASSIGNED(String iNVESTIGATOR_ASSIGNED) {
		INVESTIGATOR_ASSIGNED = iNVESTIGATOR_ASSIGNED;
	}
	public String getDECISION_ARRIVED() {
		return DECISION_ARRIVED;
	}
	public void setDECISION_ARRIVED(String dECISION_ARRIVED) {
		DECISION_ARRIVED = dECISION_ARRIVED;
	}
	public String getREASON_NO_DECISION() {
		return REASON_NO_DECISION;
	}
	public void setREASON_NO_DECISION(String rEASON_NO_DECISION) {
		REASON_NO_DECISION = rEASON_NO_DECISION;
	}
	public String getDECISION_REPORT() {
		return DECISION_REPORT;
	}
	public void setDECISION_REPORT(String dECISION_REPORT) {
		DECISION_REPORT = dECISION_REPORT;
	}
	public String getDECISION_SIGNATURE() {
		return DECISION_SIGNATURE;
	}
	public void setDECISION_SIGNATURE(String dECISION_SIGNATURE) {
		DECISION_SIGNATURE = dECISION_SIGNATURE;
	}
	public String getEMP_ACCEPT_DECISION() {
		return EMP_ACCEPT_DECISION;
	}
	public void setEMP_ACCEPT_DECISION(String eMP_ACCEPT_DECISION) {
		EMP_ACCEPT_DECISION = eMP_ACCEPT_DECISION;
	}
	public String getEMP_NOT_ACCEPT_REASON() {
		return EMP_NOT_ACCEPT_REASON;
	}
	public void setEMP_NOT_ACCEPT_REASON(String eMP_NOT_ACCEPT_REASON) {
		EMP_NOT_ACCEPT_REASON = eMP_NOT_ACCEPT_REASON;
	}
	public String getDECISION_REPORT_DATE() {
		return DECISION_REPORT_DATE;
	}
	public void setDECISION_REPORT_DATE(String dECISION_REPORT_DATE) {
		DECISION_REPORT_DATE = dECISION_REPORT_DATE;
	}
	public String getDECISION_REPORT_CONTENT() {
		return DECISION_REPORT_CONTENT;
	}
	public void setDECISION_REPORT_CONTENT(String dECISION_REPORT_CONTENT) {
		DECISION_REPORT_CONTENT = dECISION_REPORT_CONTENT;
	}
	public String getFlagButton() {
		return flagButton;
	}
	public void setFlagButton(String flagButton) {
		this.flagButton = flagButton;
	}
	public String getTATEXT_REASON() {
		return TATEXT_REASON;
	}
	public void setTATEXT_REASON(String tATEXT_REASON) {
		TATEXT_REASON = tATEXT_REASON;
	}
	public int getIsTatExtn() {
		return isTatExtn;
	}
	public void setIsTatExtn(int isTatExtn) {
		this.isTatExtn = isTatExtn;
	}
	public GridCase() {
		
	}

	@Override
	public String toString() {
		return "GridCase [GRVDETID=" + GRVDETID + ", CASEID=" + CASEID + ", HIERCODE=" + HIERCODE + ", HIERORDER="
				+ HIERORDER + ", TAT_START_DATE=" + TAT_START_DATE + ", TAT_ACTUAL_END_DATE=" + TAT_ACTUAL_END_DATE
				+ ", CURRENT_ROW_COMPLETED=" + CURRENT_ROW_COMPLETED + ", CURRENT_ROW_ACTIVE=" + CURRENT_ROW_ACTIVE
				+ ", IS_ACTIVE=" + IS_ACTIVE + ", INVESTIGATOR_EMPLOYEE_ID=" + INVESTIGATOR_EMPLOYEE_ID + ", NAME="
				+ NAME + ", RE_ASSIGN=" + RE_ASSIGN + ", REOPEN_DATE=" + REOPEN_DATE + ", REOPEN_HIERORDER="
				+ REOPEN_HIERORDER + ", REOPEN_REASON=" + REOPEN_REASON + ", BUFFERDAYS=" + BUFFERDAYS + ", CASENUMBER="
				+ CASENUMBER + ", MAIN_CATEGORY_CODE=" + MAIN_CATEGORY_CODE + ", SUB_CATEGORY_CODE=" + SUB_CATEGORY_CODE
				+ ", TAT_EXTENDED=" + TAT_EXTENDED + ", TAT_EXTENDED_EMPLOYEE_ID=" + TAT_EXTENDED_EMPLOYEE_ID
				+ ", TAT_END_DATE=" + TAT_END_DATE + ", INVESTIGATOR_NEEDED=" + INVESTIGATOR_NEEDED
				+ ", INVESTIGATOR_ASSIGNED=" + INVESTIGATOR_ASSIGNED + ", DECISION_ARRIVED=" + DECISION_ARRIVED
				+ ", REASON_NO_DECISION=" + REASON_NO_DECISION + ", DECISION_REPORT=" + DECISION_REPORT
				+ ", DECISION_SIGNATURE=" + DECISION_SIGNATURE + ", EMP_ACCEPT_DECISION=" + EMP_ACCEPT_DECISION
				+ ", EMP_NOT_ACCEPT_REASON=" + EMP_NOT_ACCEPT_REASON + ", DECISION_REPORT_DATE=" + DECISION_REPORT_DATE
				+ ", DECISION_REPORT_CONTENT=" + DECISION_REPORT_CONTENT + ", flagButton=" + flagButton
				+ ", TATEXT_REASON=" + TATEXT_REASON + ", isTatExtn=" + isTatExtn + "]";
	}
	
	
}
